"""Add is_in_stock column

Revision ID: b9ac0a51f306
Revises: 1fbfa43fdc29
Create Date: 2025-06-29 15:13:19.367554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ac0a51f306'
down_revision = '1fbfa43fdc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
